server:
  port: 9091

spring:
  application:
    name: GPT_First
  main:
    allow-bean-definition-overriding: true

openai:
  url: https://api.openai.com
  token: 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
