server:
  port: 9091

spring:
  application:
    name: GPT_First
  main:
    allow-bean-definition-overriding: true

open:
  ai:
    token: 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
    url: https://api.openai.com
