server:
  port: 9091

spring:
  application:
    name: GPT_First
  main:
    allow-bean-definition-overriding: true

openai:
  url: https://api.openai.com
  token: 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
