server:
  port: 9091

spring:
  application:
    name: gpt-java
  main:
    allow-bean-definition-overriding: true

openai:
  url: https://api.openai.com
  token: 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

logging:
  config: classpath:log4j2.xml
